name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - uses: ./.github/actions/setup

      - run: yarn build
      - run: yarn test
  
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - uses: ./.github/actions/setup

      - run: yarn build

      - name: Run contract coverage
        run: yarn coverage
        env:
          # to solve problem of memory leak https://stackoverflow.com/a/59572966
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage
